# CI/CD Configuration for AI-Interlinq Auto-Improvement System
# LAW-001 Compliant Configuration

auto_improvement:
  enabled: true
  schedule: "0 */6 * * *"  # Every 6 hours
  triggers:
    - push
    - pull_request
    - schedule
    - workflow_dispatch
  branches:
    - main
    - develop
  law_001_compliance: true

code_analysis:
  enabled: true
  tools:
    - pylint
    - black
    - mypy
    - bandit
    - isort
    - flake8
  quality_gates:
    min_coverage: 80
    max_complexity: 10
    security_scan: true
  
testing:
  enabled: true
  frameworks:
    - pytest
    - unittest
    - integration_tests
    - law_ai_compliance_tests
  parallel_execution: true
  coverage_reporting: true
  
auto_commit:
  enabled: true
  secret: "mupoese_key"
  branch_protection: false
  commit_message_template: "🤖 Auto-improvement: {improvement_type} - {timestamp}"
  max_commits_per_cycle: 5
  auto_push: true
  create_pr_for_major_changes: true

law_ai_integration:
  compliance_check: true
  snapshot_generation: true
  learning_cycle_integration: true
  memory_system_integration: true
  pattern_detection: true
  governance_validation: true

security:
  secret_scanning: true
  dependency_scanning: true
  code_scanning: true
  vulnerability_reporting: true
  
performance:
  benchmarking: true
  performance_regression_detection: true
  optimization_recommendations: true
  
monitoring:
  pipeline_metrics: true
  success_rate_tracking: true
  improvement_impact_analysis: true
  cost_optimization: true

improvement_detection:
  code_smells: true
  performance_bottlenecks: true
  security_vulnerabilities: true
  architecture_improvements: true
  refactoring_opportunities: true
  documentation_gaps: true

auto_implementation:
  feature_generation: true
  code_generation: true
  test_generation: true
  documentation_generation: true
  integration_testing: true
  rollback_capability: true

notifications:
  success_notifications: false
  failure_notifications: true
  summary_reports: true
  stakeholder_updates: true

# Environment-specific settings
environments:
  development:
    auto_commit: true
    extensive_testing: true
  production:
    auto_commit: false
    manual_approval_required: true
    enhanced_validation: true

# Compliance and governance
governance:
  require_law_001_compliance: true
  snapshot_validation: true
  pattern_analysis: true
  memory_integration: true
  admin_override: "mupoese_admin_core"